# Generated by Django 3.2.7 on 2021-09-09 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
