# Generated by Django 3.2.7 on 2021-09-15 09:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210915_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 15, 9, 49, 30, 321790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 15, 9, 49, 30, 322084, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item', to='order.order'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 15, 9, 49, 30, 323245, tzinfo=utc)),
        ),
    ]
