# Generated by Django 3.2.7 on 2021-09-15 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210915_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2021, 9, 15, 12, 11, 36, 426753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2021, 9, 15, 12, 11, 36, 427059, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 15, 12, 11, 36, 428388, tzinfo=utc)),
        ),
    ]
