# Generated by Django 3.2.7 on 2021-09-15 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productmodel_date_added'),
        ('order', '0004_auto_20210915_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2021, 9, 15, 14, 24, 30, 628397, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2021, 9, 15, 14, 24, 30, 628698, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ManyToManyField(null=True, to='products.ProductModel'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 15, 14, 24, 30, 630250, tzinfo=utc)),
        ),
    ]
