# Generated by Django 3.2.7 on 2021-09-15 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productmodel_date_added'),
        ('order', '0005_auto_20210915_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2021, 9, 15, 14, 33, 54, 474885, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2021, 9, 15, 14, 33, 54, 475190, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productmodel'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 15, 14, 33, 54, 476479, tzinfo=utc)),
        ),
    ]
