# Generated by Django 3.2.7 on 2021-09-11 08:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210911_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('slug', models.SlugField(max_length=255)),
                ('date_added', models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 11, 8, 51, 33, 355567))),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.categorymodel'),
        ),
    ]
