# Generated by Django 3.2.7 on 2021-09-11 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.timezone),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnail/'),
        ),
    ]
