# Generated by Django 3.2.7 on 2021-09-11 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210911_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.date),
        ),
    ]
