# Generated by Django 3.2.7 on 2021-09-15 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productmodel_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 15, 8, 16, 4, 454158, tzinfo=utc)),
        ),
    ]
