# Generated by Django 3.2.7 on 2021-09-15 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productmodel_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 15, 9, 49, 30, 318284, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
