# Generated by Django 3.2.7 on 2021-09-15 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productmodel_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 15, 14, 33, 54, 471252, tzinfo=utc)),
        ),
    ]
